"""empty message

Revision ID: 4a4cfa7533d1
Revises: 
Create Date: 2021-06-20 19:46:01.471093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4cfa7533d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_feedback_email'), 'feedback', ['email'], unique=False)
    op.create_index(op.f('ix_feedback_username'), 'feedback', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_username'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_email'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
